spring:
  main:
    banner-mode: "off"
  application:
    name: invernada
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      resource-id: invernada-web
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/invernada
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  datasource:
    url: jdbc:mariadb://localhost:3306/invernada
    username: invernada
    password: invernadaPwd
    driver-class-name: org.mariadb.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG